using System.Text;
using System.Text.Json;
using Blackpaw.Analysis;
using Blackpaw.Data;

namespace Blackpaw.Reporting;

public class ReportData
{
    public required RunRecord Run { get; init; }
    public List<SystemSample> SystemSamples { get; init; } = [];
    public List<ProcessSample> ProcessSamples { get; init; } = [];
    public List<DotNetRuntimeSample> DotNetRuntimeSamples { get; init; } = [];
    public List<DotNetHttpSample> DotNetHttpSamples { get; init; } = [];
    public List<SqlDmvSample> SqlDmvSamples { get; init; } = [];
    public List<DbSnapshot> DbSnapshots { get; init; } = [];
    public List<Marker> Markers { get; init; } = [];
}

public static class ReportGenerator
{
    public static ReportData LoadReportData(DatabaseService db, long runId)
    {
        var run = db.GetRunById(runId);
        if (run == null)
            throw new ArgumentException($"Run {runId} not found");

        return new ReportData
        {
            Run = run,
            SystemSamples = db.GetSystemSamples(runId),
            ProcessSamples = db.GetProcessSamplesForRun(runId),
            DotNetRuntimeSamples = db.GetDotNetRuntimeSamples(runId),
            DotNetHttpSamples = db.GetDotNetHttpSamples(runId),
            SqlDmvSamples = db.GetSqlDmvSamples(runId),
            DbSnapshots = db.GetDbSnapshots(runId),
            Markers = db.GetMarkers(runId)
        };
    }

    public static string GenerateHtml(ReportData data)
    {
        var sb = new StringBuilder();
        var run = data.Run;

        // Calculate summary statistics for enhanced tables
        var summary = RunSummary.FromReportData(data);

        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("  <meta charset=\"UTF-8\">");
        sb.AppendLine("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        sb.AppendLine($"  <title>Blackpaw Report - {HtmlEncode(run.ScenarioName)}</title>");
        sb.AppendLine("  <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>");
        AppendStyles(sb);
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");

        // Header
        sb.AppendLine("  <header>");
        sb.AppendLine("    <h1>Blackpaw Performance Report</h1>");
        sb.AppendLine($"    <p class=\"subtitle\">Scenario: <strong>{HtmlEncode(run.ScenarioName)}</strong></p>");
        sb.AppendLine("  </header>");

        sb.AppendLine("  <main>");

        // Summary section
        AppendSummarySection(sb, run);

        // System metrics section
        if (data.SystemSamples.Count > 0)
        {
            AppendSystemMetricsSection(sb, data.SystemSamples, summary.System);
        }

        // Process metrics section
        if (data.ProcessSamples.Count > 0)
        {
            AppendProcessMetricsSection(sb, data.SystemSamples, data.ProcessSamples, summary.Processes);
        }

        // .NET Runtime section
        if (data.DotNetRuntimeSamples.Count > 0)
        {
            AppendDotNetRuntimeSection(sb, data.DotNetRuntimeSamples, summary.DotNetApps);
        }

        // HTTP section
        if (data.DotNetHttpSamples.Count > 0)
        {
            AppendHttpSection(sb, data.DotNetHttpSamples, summary.HttpEndpoints);
        }

        // SQL DMV section
        if (data.SqlDmvSamples.Count > 0)
        {
            AppendSqlSection(sb, data.SqlDmvSamples, summary.Sql);
        }

        // Markers section
        if (data.Markers.Count > 0)
        {
            AppendMarkersSection(sb, data.Markers, run.StartedAtUtc);
        }

        sb.AppendLine("  </main>");

        // Footer
        sb.AppendLine("  <footer>");
        sb.AppendLine($"    <p>Generated by Blackpaw v{run.ProbeVersion} on {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC</p>");
        sb.AppendLine("    <p class=\"memorial\">In memory of Oliver</p>");
        sb.AppendLine("  </footer>");

        // Embed data and chart scripts
        AppendChartScripts(sb, data);

        sb.AppendLine("</body>");
        sb.AppendLine("</html>");

        return sb.ToString();
    }

    private static void AppendStyles(StringBuilder sb)
    {
        sb.AppendLine("  <style>");
        sb.AppendLine(@"
    :root {
      --bg: #2d2d2d;
      --bg-card: #3a3a3a;
      --bg-hover: #454545;
      --text: #e8e8e8;
      --text-dim: #a0a0a0;
      --accent: #4a4a4a;
      --highlight: #d4a574;
      --highlight-soft: #c49a6c;
      --success: #7eb77f;
      --warning: #d4a574;
      --error: #c77272;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: var(--bg);
      color: var(--text);
      line-height: 1.6;
      padding: 2rem;
    }
    header {
      text-align: center;
      margin-bottom: 2rem;
      padding-bottom: 1rem;
      border-bottom: 1px solid var(--accent);
    }
    header h1 { color: var(--highlight); margin-bottom: 0.5rem; letter-spacing: 0.5px; }
    .subtitle { color: var(--text-dim); }
    main { max-width: 1400px; margin: 0 auto; }
    section {
      background: var(--bg-card);
      border-radius: 8px;
      padding: 1.5rem;
      margin-bottom: 1.5rem;
      border: 1px solid var(--accent);
    }
    section h2 {
      color: var(--highlight);
      margin-bottom: 1rem;
      padding-bottom: 0.5rem;
      border-bottom: 1px solid var(--accent);
      font-weight: 500;
    }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; }
    .stat-card {
      background: var(--accent);
      padding: 1rem;
      border-radius: 6px;
      border: 1px solid #555;
    }
    .stat-card .label { color: var(--text-dim); font-size: 0.85rem; }
    .stat-card .value { font-size: 1.25rem; font-weight: 600; color: var(--text); }
    .chart-container {
      position: relative;
      height: 300px;
      margin: 1rem 0;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 1rem 0;
    }
    th, td {
      padding: 0.75rem;
      text-align: left;
      border-bottom: 1px solid var(--accent);
    }
    th { color: var(--text-dim); font-weight: 500; }
    tr:hover { background: var(--bg-hover); }
    .marker-info { color: var(--success); }
    .marker-warning { color: var(--warning); }
    .marker-error { color: var(--error); }
    h3 {
      color: var(--text);
      margin: 1.5rem 0 0.75rem 0;
      font-size: 1.1rem;
      font-weight: 500;
    }
    .stats-table {
      font-size: 0.9rem;
    }
    .stats-table th {
      background: var(--accent);
    }
    .stats-table td {
      font-variant-numeric: tabular-nums;
    }
    .stats-table code {
      background: var(--bg);
      padding: 0.2rem 0.4rem;
      border-radius: 3px;
      font-size: 0.85rem;
    }
    .stats-table .success { color: var(--success); font-weight: 500; }
    .stats-table .warning { color: var(--warning); font-weight: 500; }
    .stats-table .error { color: var(--error); font-weight: 500; }
    footer {
      text-align: center;
      padding: 2rem 0;
      color: var(--text-dim);
      font-size: 0.85rem;
    }
    .memorial {
      margin-top: 0.5rem;
      font-style: italic;
      color: var(--highlight-soft);
    }
    ");
        sb.AppendLine("  </style>");
    }

    private static void AppendSummarySection(StringBuilder sb, RunRecord run)
    {
        sb.AppendLine("    <section id=\"summary\">");
        sb.AppendLine("      <h2>Run Summary</h2>");
        sb.AppendLine("      <div class=\"grid\">");

        AppendStatCard(sb, "Run ID", run.RunId.ToString());
        AppendStatCard(sb, "Started", run.StartedAtUtc.ToString("yyyy-MM-dd HH:mm:ss UTC"));
        AppendStatCard(sb, "Duration", run.DurationSeconds.HasValue ? $"{run.DurationSeconds:N1}s" : "In Progress");
        AppendStatCard(sb, "Machine", run.MachineName);
        AppendStatCard(sb, "OS", run.OsVersion);
        AppendStatCard(sb, "CPU Cores", run.CpuLogicalCoreCount.ToString());
        AppendStatCard(sb, "Memory", $"{run.TotalPhysicalMemoryMb:N0} MB");
        if (!string.IsNullOrEmpty(run.WorkloadType))
            AppendStatCard(sb, "Workload", run.WorkloadType);
        if (!string.IsNullOrEmpty(run.Notes))
            AppendStatCard(sb, "Notes", run.Notes);

        sb.AppendLine("      </div>");
        sb.AppendLine("    </section>");
    }

    private static void AppendStatCard(StringBuilder sb, string label, string value)
    {
        sb.AppendLine($"        <div class=\"stat-card\"><div class=\"label\">{HtmlEncode(label)}</div><div class=\"value\">{HtmlEncode(value)}</div></div>");
    }

    private static void AppendSystemMetricsSection(StringBuilder sb, List<SystemSample> samples, SystemMetricsSummary stats)
    {
        sb.AppendLine("    <section id=\"system\">");
        sb.AppendLine("      <h2>System Metrics</h2>");

        // Quick summary cards
        sb.AppendLine("      <div class=\"grid\">");
        AppendStatCard(sb, "Avg CPU", $"{stats.Cpu.Avg:N1}%");
        AppendStatCard(sb, "P95 CPU", $"{stats.Cpu.P95:N1}%");
        AppendStatCard(sb, "Max CPU", $"{stats.Cpu.Max:N1}%");
        AppendStatCard(sb, "Avg Memory", $"{stats.MemoryMb.Avg:N0} MB");
        AppendStatCard(sb, "Max Memory", $"{stats.MemoryMb.Max:N0} MB");
        AppendStatCard(sb, "Samples", samples.Count.ToString());
        sb.AppendLine("      </div>");

        // Detailed statistics table
        sb.AppendLine("      <h3>Detailed Statistics</h3>");
        sb.AppendLine("      <table class=\"stats-table\">");
        sb.AppendLine("        <thead><tr><th>Metric</th><th>Min</th><th>Avg</th><th>P50</th><th>P95</th><th>Max</th></tr></thead>");
        sb.AppendLine("        <tbody>");
        AppendStatsRow(sb, "CPU %", stats.Cpu, "%");
        AppendStatsRow(sb, "Memory (MB)", stats.MemoryMb, "");
        if (stats.DiskReadBytesPerSec.HasData)
        {
            AppendStatsRowBytes(sb, "Disk Read", stats.DiskReadBytesPerSec);
            AppendStatsRowBytes(sb, "Disk Write", stats.DiskWriteBytesPerSec);
        }
        if (stats.NetSentBytesPerSec.HasData)
        {
            AppendStatsRowBytes(sb, "Net Sent", stats.NetSentBytesPerSec);
            AppendStatsRowBytes(sb, "Net Received", stats.NetReceivedBytesPerSec);
        }
        sb.AppendLine("        </tbody>");
        sb.AppendLine("      </table>");

        sb.AppendLine("      <div class=\"chart-container\"><canvas id=\"cpuMemChart\"></canvas></div>");
        sb.AppendLine("      <div class=\"chart-container\"><canvas id=\"diskChart\"></canvas></div>");
        sb.AppendLine("      <div class=\"chart-container\"><canvas id=\"networkChart\"></canvas></div>");
        sb.AppendLine("    </section>");
    }

    private static void AppendStatsRow(StringBuilder sb, string metric, MetricStats stats, string unit)
    {
        if (!stats.HasData) return;
        var u = string.IsNullOrEmpty(unit) ? "" : unit;
        sb.AppendLine($"          <tr><td>{HtmlEncode(metric)}</td><td>{stats.Min:N1}{u}</td><td>{stats.Avg:N1}{u}</td><td>{stats.P50:N1}{u}</td><td>{stats.P95:N1}{u}</td><td>{stats.Max:N1}{u}</td></tr>");
    }

    private static void AppendStatsRowBytes(StringBuilder sb, string metric, MetricStats stats)
    {
        if (!stats.HasData) return;
        sb.AppendLine($"          <tr><td>{HtmlEncode(metric)}</td><td>{FormatBytes(stats.Min)}/s</td><td>{FormatBytes(stats.Avg)}/s</td><td>{FormatBytes(stats.P50)}/s</td><td>{FormatBytes(stats.P95)}/s</td><td>{FormatBytes(stats.Max)}/s</td></tr>");
    }

    private static string FormatBytes(double bytes)
    {
        return bytes switch
        {
            >= 1_073_741_824 => $"{bytes / 1_073_741_824:N1} GB",
            >= 1_048_576 => $"{bytes / 1_048_576:N1} MB",
            >= 1024 => $"{bytes / 1024:N1} KB",
            _ => $"{bytes:N0} B"
        };
    }

    private static void AppendProcessMetricsSection(StringBuilder sb, List<SystemSample> systemSamples, List<ProcessSample> processSamples, List<ProcessMetricsSummary> processStats)
    {
        var processes = processSamples.Select(p => p.ProcessName).Distinct().OrderBy(p => p).ToList();

        sb.AppendLine("    <section id=\"processes\">");
        sb.AppendLine("      <h2>Process Metrics</h2>");
        sb.AppendLine($"      <p>Tracked processes: {string.Join(", ", processes.Select(HtmlEncode))}</p>");

        // Per-process summary table
        sb.AppendLine("      <table class=\"stats-table\">");
        sb.AppendLine("        <thead><tr><th>Process</th><th>CPU Avg</th><th>CPU P95</th><th>CPU Max</th><th>Mem Avg</th><th>Mem P95</th><th>Mem Max</th><th>Threads</th></tr></thead>");
        sb.AppendLine("        <tbody>");
        foreach (var proc in processStats)
        {
            sb.AppendLine($"          <tr>");
            sb.AppendLine($"            <td><strong>{HtmlEncode(proc.ProcessName)}</strong></td>");
            sb.AppendLine($"            <td>{proc.Cpu.Avg:N1}%</td>");
            sb.AppendLine($"            <td>{proc.Cpu.P95:N1}%</td>");
            sb.AppendLine($"            <td>{proc.Cpu.Max:N1}%</td>");
            sb.AppendLine($"            <td>{proc.WorkingSetMb.Avg:N0} MB</td>");
            sb.AppendLine($"            <td>{proc.WorkingSetMb.P95:N0} MB</td>");
            sb.AppendLine($"            <td>{proc.WorkingSetMb.Max:N0} MB</td>");
            sb.AppendLine($"            <td>{proc.ThreadCount.Avg:N0} (max {proc.ThreadCount.Max:N0})</td>");
            sb.AppendLine($"          </tr>");
        }
        sb.AppendLine("        </tbody>");
        sb.AppendLine("      </table>");

        sb.AppendLine("      <div class=\"chart-container\"><canvas id=\"processCpuChart\"></canvas></div>");
        sb.AppendLine("      <div class=\"chart-container\"><canvas id=\"processMemChart\"></canvas></div>");
        sb.AppendLine("    </section>");
    }

    private static void AppendDotNetRuntimeSection(StringBuilder sb, List<DotNetRuntimeSample> samples, List<DotNetRuntimeSummary> appStats)
    {
        var apps = samples.Select(s => s.AppName).Distinct().ToList();

        sb.AppendLine("    <section id=\"dotnet\">");
        sb.AppendLine("      <h2>.NET Runtime Metrics</h2>");
        sb.AppendLine($"      <p>Monitored apps: {string.Join(", ", apps.Select(HtmlEncode))}</p>");

        // Per-app summary table
        foreach (var app in appStats)
        {
            sb.AppendLine($"      <h3>{HtmlEncode(app.AppName)}</h3>");
            sb.AppendLine("      <div class=\"grid\">");
            AppendStatCard(sb, "Heap Avg", $"{app.HeapSizeMb.Avg:N1} MB");
            AppendStatCard(sb, "Heap Max", $"{app.HeapSizeMb.Max:N1} MB");
            AppendStatCard(sb, "GC Time Avg", $"{app.GcTimePercent.Avg:N2}%");
            AppendStatCard(sb, "GC Time Max", $"{app.GcTimePercent.Max:N2}%");
            AppendStatCard(sb, "Exceptions", app.TotalExceptionsEstimate.ToString("N0"));
            sb.AppendLine("      </div>");

            sb.AppendLine("      <table class=\"stats-table\">");
            sb.AppendLine("        <thead><tr><th>Metric</th><th>Total</th><th>Avg/s</th><th>Max/s</th></tr></thead>");
            sb.AppendLine("        <tbody>");
            sb.AppendLine($"          <tr><td>Gen0 Collections</td><td>{app.TotalGen0Collections:N0}</td><td>{app.Gen0CollectionsPerSec.Avg:N2}</td><td>{app.Gen0CollectionsPerSec.Max:N2}</td></tr>");
            sb.AppendLine($"          <tr><td>Gen1 Collections</td><td>{app.TotalGen1Collections:N0}</td><td>{app.Gen1CollectionsPerSec.Avg:N2}</td><td>{app.Gen1CollectionsPerSec.Max:N2}</td></tr>");
            sb.AppendLine($"          <tr><td>Gen2 Collections</td><td>{app.TotalGen2Collections:N0}</td><td>{app.Gen2CollectionsPerSec.Avg:N2}</td><td>{app.Gen2CollectionsPerSec.Max:N2}</td></tr>");
            if (app.ThreadPoolThreadCount.HasData)
            {
                sb.AppendLine($"          <tr><td>ThreadPool Threads</td><td>—</td><td>{app.ThreadPoolThreadCount.Avg:N0}</td><td>{app.ThreadPoolThreadCount.Max:N0}</td></tr>");
            }
            if (app.ThreadPoolQueueLength.HasData)
            {
                sb.AppendLine($"          <tr><td>ThreadPool Queue</td><td>—</td><td>{app.ThreadPoolQueueLength.Avg:N1}</td><td>{app.ThreadPoolQueueLength.Max:N0}</td></tr>");
            }
            sb.AppendLine("        </tbody>");
            sb.AppendLine("      </table>");
        }

        sb.AppendLine("      <div class=\"chart-container\"><canvas id=\"dotnetHeapChart\"></canvas></div>");
        sb.AppendLine("      <div class=\"chart-container\"><canvas id=\"dotnetGcChart\"></canvas></div>");
        sb.AppendLine("    </section>");
    }

    private static void AppendHttpSection(StringBuilder sb, List<DotNetHttpSample> samples, List<HttpEndpointSummary> endpointStats)
    {
        var totalRequests = samples.Sum(s => s.RequestCount);
        var totalSuccess = samples.Sum(s => s.SuccessCount);
        var total4xx = samples.Sum(s => s.Error4xxCount);
        var total5xx = samples.Sum(s => s.Error5xxCount);

        sb.AppendLine("    <section id=\"http\">");
        sb.AppendLine("      <h2>HTTP Request Metrics</h2>");
        sb.AppendLine("      <div class=\"grid\">");
        AppendStatCard(sb, "Total Requests", totalRequests.ToString("N0"));
        AppendStatCard(sb, "Success", totalSuccess.ToString("N0"));
        AppendStatCard(sb, "4xx Errors", total4xx.ToString("N0"));
        AppendStatCard(sb, "5xx Errors", total5xx.ToString("N0"));
        sb.AppendLine("      </div>");

        // Per-endpoint breakdown table
        if (endpointStats.Count > 0)
        {
            sb.AppendLine("      <h3>Endpoint Breakdown</h3>");
            sb.AppendLine("      <table class=\"stats-table\">");
            sb.AppendLine("        <thead><tr><th>Endpoint</th><th>Requests</th><th>Latency Avg</th><th>Latency P50</th><th>Latency P95</th><th>Latency Max</th><th>4xx</th><th>5xx</th><th>Success %</th></tr></thead>");
            sb.AppendLine("        <tbody>");
            foreach (var ep in endpointStats)
            {
                var successClass = ep.SuccessRate >= 99 ? "success" : ep.SuccessRate >= 95 ? "" : "warning";
                sb.AppendLine($"          <tr>");
                sb.AppendLine($"            <td><code>{HtmlEncode(ep.Endpoint)}</code></td>");
                sb.AppendLine($"            <td>{ep.TotalRequests:N0}</td>");
                sb.AppendLine($"            <td>{ep.LatencyMs.Avg:N1} ms</td>");
                sb.AppendLine($"            <td>{ep.LatencyMs.P50:N1} ms</td>");
                sb.AppendLine($"            <td>{ep.LatencyMs.P95:N1} ms</td>");
                sb.AppendLine($"            <td>{ep.MaxLatencyMs:N1} ms</td>");
                sb.AppendLine($"            <td>{ep.Total4xx:N0}</td>");
                sb.AppendLine($"            <td>{ep.Total5xx:N0}</td>");
                sb.AppendLine($"            <td class=\"{successClass}\">{ep.SuccessRate:N1}%</td>");
                sb.AppendLine($"          </tr>");
            }
            sb.AppendLine("        </tbody>");
            sb.AppendLine("      </table>");
        }

        sb.AppendLine("      <div class=\"chart-container\"><canvas id=\"httpChart\"></canvas></div>");
        sb.AppendLine("    </section>");
    }

    private static void AppendSqlSection(StringBuilder sb, List<SqlDmvSample> samples, SqlMetricsSummary? stats)
    {
        sb.AppendLine("    <section id=\"sql\">");
        sb.AppendLine("      <h2>SQL Server Metrics</h2>");

        if (stats != null)
        {
            sb.AppendLine("      <div class=\"grid\">");
            AppendStatCard(sb, "Active Requests Avg", $"{stats.ActiveRequests.Avg:N1}");
            AppendStatCard(sb, "Active Requests Max", $"{stats.ActiveRequests.Max:N0}");
            AppendStatCard(sb, "Blocked Requests Max", $"{stats.BlockedRequests.Max:N0}");
            AppendStatCard(sb, "Wait Time Avg", $"{stats.TotalWaitTimeMs.Avg:N1} ms");
            AppendStatCard(sb, "Connections Avg", $"{stats.UserConnections.Avg:N0}");
            AppendStatCard(sb, "Samples", stats.SampleCount.ToString());
            sb.AppendLine("      </div>");

            sb.AppendLine("      <table class=\"stats-table\">");
            sb.AppendLine("        <thead><tr><th>Metric</th><th>Min</th><th>Avg</th><th>P50</th><th>P95</th><th>Max</th></tr></thead>");
            sb.AppendLine("        <tbody>");
            AppendStatsRow(sb, "Active Requests", stats.ActiveRequests, "");
            AppendStatsRow(sb, "Blocked Requests", stats.BlockedRequests, "");
            AppendStatsRow(sb, "Wait Time (ms)", stats.TotalWaitTimeMs, "");
            AppendStatsRow(sb, "User Connections", stats.UserConnections, "");
            sb.AppendLine("        </tbody>");
            sb.AppendLine("      </table>");
        }

        sb.AppendLine("      <div class=\"chart-container\"><canvas id=\"sqlChart\"></canvas></div>");
        sb.AppendLine("    </section>");
    }

    private static void AppendMarkersSection(StringBuilder sb, List<Marker> markers, DateTime runStart)
    {
        sb.AppendLine("    <section id=\"markers\">");
        sb.AppendLine("      <h2>Events &amp; Markers</h2>");
        sb.AppendLine("      <table>");
        sb.AppendLine("        <thead><tr><th>Time</th><th>Offset</th><th>Type</th><th>Label</th></tr></thead>");
        sb.AppendLine("        <tbody>");

        foreach (var m in markers)
        {
            var offset = (m.TimestampUtc - runStart).TotalSeconds;
            var levelClass = m.Level?.ToLowerInvariant() switch
            {
                "warning" => "marker-warning",
                "error" => "marker-error",
                _ => "marker-info"
            };
            sb.AppendLine($"          <tr class=\"{levelClass}\"><td>{m.TimestampUtc:HH:mm:ss}</td><td>+{offset:N1}s</td><td>{HtmlEncode(m.MarkerType)}</td><td>{HtmlEncode(m.Label)}</td></tr>");
        }

        sb.AppendLine("        </tbody>");
        sb.AppendLine("      </table>");
        sb.AppendLine("    </section>");
    }

    private static void AppendChartScripts(StringBuilder sb, ReportData data)
    {
        sb.AppendLine("  <script>");

        // Serialize data to JSON for charts
        var jsonOptions = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };

        var systemData = data.SystemSamples.Select(s => new
        {
            t = s.TimestampUtc.ToString("o"),
            cpu = s.CpuTotalPercent,
            mem = s.MemoryInUseMb,
            diskR = s.DiskReadBytesPerSec,
            diskW = s.DiskWriteBytesPerSec,
            netS = s.NetBytesSentPerSec,
            netR = s.NetBytesReceivedPerSec
        }).ToList();

        sb.AppendLine($"    const systemData = {JsonSerializer.Serialize(systemData, jsonOptions)};");

        // Process data grouped by process name with timestamps
        var sampleTimestamps = data.SystemSamples.ToDictionary(s => s.SampleId, s => s.TimestampUtc);
        var processData = data.ProcessSamples
            .Where(p => sampleTimestamps.ContainsKey(p.SampleId))
            .Select(p => new
            {
                t = sampleTimestamps[p.SampleId].ToString("o"),
                name = p.ProcessName,
                cpu = p.CpuPercent,
                mem = p.WorkingSetMb
            }).ToList();

        sb.AppendLine($"    const processData = {JsonSerializer.Serialize(processData, jsonOptions)};");

        // .NET Runtime data
        var dotnetData = data.DotNetRuntimeSamples.Select(s => new
        {
            t = s.TimestampUtc.ToString("o"),
            app = s.AppName,
            heap = s.HeapSizeMb,
            gcTime = s.GcTimePercent,
            gen0 = s.Gen0CollectionsPerSec,
            gen1 = s.Gen1CollectionsPerSec,
            gen2 = s.Gen2CollectionsPerSec
        }).ToList();

        sb.AppendLine($"    const dotnetData = {JsonSerializer.Serialize(dotnetData, jsonOptions)};");

        // HTTP data
        var httpData = data.DotNetHttpSamples.Select(s => new
        {
            t = s.TimestampUtc.ToString("o"),
            endpoint = s.EndpointGroup,
            count = s.RequestCount,
            latency = s.AvgDurationMs
        }).ToList();

        sb.AppendLine($"    const httpData = {JsonSerializer.Serialize(httpData, jsonOptions)};");

        // SQL data
        var sqlData = data.SqlDmvSamples.Select(s => new
        {
            t = s.TimestampUtc.ToString("o"),
            active = s.ActiveRequestsCount,
            wait = s.TotalWaitTimeMs,
            blocked = s.BlockedRequestsCount
        }).ToList();

        sb.AppendLine($"    const sqlData = {JsonSerializer.Serialize(sqlData, jsonOptions)};");

        // Chart initialization code
        sb.AppendLine(@"
    const chartDefaults = {
      responsive: true,
      maintainAspectRatio: false,
      plugins: { legend: { labels: { color: '#e8e8e8' } } },
      scales: {
        x: { ticks: { color: '#a0a0a0' }, grid: { color: '#4a4a4a' } },
        y: { ticks: { color: '#a0a0a0' }, grid: { color: '#4a4a4a' } }
      }
    };

    // System CPU & Memory Chart
    if (systemData.length > 0 && document.getElementById('cpuMemChart')) {
      new Chart(document.getElementById('cpuMemChart'), {
        type: 'line',
        data: {
          labels: systemData.map(d => new Date(d.t).toLocaleTimeString()),
          datasets: [
            { label: 'CPU %', data: systemData.map(d => d.cpu), borderColor: '#e94560', tension: 0.1 },
            { label: 'Memory MB', data: systemData.map(d => d.mem), borderColor: '#4ade80', yAxisID: 'y1', tension: 0.1 }
          ]
        },
        options: {
          ...chartDefaults,
          scales: {
            ...chartDefaults.scales,
            y: { ...chartDefaults.scales.y, position: 'left', title: { display: true, text: 'CPU %', color: '#888' } },
            y1: { position: 'right', ticks: { color: '#888' }, grid: { drawOnChartArea: false }, title: { display: true, text: 'Memory MB', color: '#888' } }
          }
        }
      });
    }

    // Disk Chart
    if (systemData.length > 0 && document.getElementById('diskChart')) {
      new Chart(document.getElementById('diskChart'), {
        type: 'line',
        data: {
          labels: systemData.map(d => new Date(d.t).toLocaleTimeString()),
          datasets: [
            { label: 'Read B/s', data: systemData.map(d => d.diskR), borderColor: '#60a5fa', tension: 0.1 },
            { label: 'Write B/s', data: systemData.map(d => d.diskW), borderColor: '#f472b6', tension: 0.1 }
          ]
        },
        options: chartDefaults
      });
    }

    // Network Chart
    if (systemData.length > 0 && document.getElementById('networkChart')) {
      new Chart(document.getElementById('networkChart'), {
        type: 'line',
        data: {
          labels: systemData.map(d => new Date(d.t).toLocaleTimeString()),
          datasets: [
            { label: 'Sent B/s', data: systemData.map(d => d.netS), borderColor: '#a78bfa', tension: 0.1 },
            { label: 'Received B/s', data: systemData.map(d => d.netR), borderColor: '#fbbf24', tension: 0.1 }
          ]
        },
        options: chartDefaults
      });
    }

    // Process CPU Chart
    if (processData.length > 0 && document.getElementById('processCpuChart')) {
      const processes = [...new Set(processData.map(d => d.name))];
      const colors = ['#e94560', '#4ade80', '#60a5fa', '#fbbf24', '#a78bfa', '#f472b6'];
      const timestamps = [...new Set(processData.map(d => d.t))].sort();

      new Chart(document.getElementById('processCpuChart'), {
        type: 'line',
        data: {
          labels: timestamps.map(t => new Date(t).toLocaleTimeString()),
          datasets: processes.map((proc, i) => ({
            label: proc,
            data: timestamps.map(t => {
              const sample = processData.find(d => d.t === t && d.name === proc);
              return sample ? sample.cpu : null;
            }),
            borderColor: colors[i % colors.length],
            tension: 0.1
          }))
        },
        options: { ...chartDefaults, plugins: { ...chartDefaults.plugins, title: { display: true, text: 'Process CPU %', color: '#eee' } } }
      });
    }

    // Process Memory Chart
    if (processData.length > 0 && document.getElementById('processMemChart')) {
      const processes = [...new Set(processData.map(d => d.name))];
      const colors = ['#e94560', '#4ade80', '#60a5fa', '#fbbf24', '#a78bfa', '#f472b6'];
      const timestamps = [...new Set(processData.map(d => d.t))].sort();

      new Chart(document.getElementById('processMemChart'), {
        type: 'line',
        data: {
          labels: timestamps.map(t => new Date(t).toLocaleTimeString()),
          datasets: processes.map((proc, i) => ({
            label: proc,
            data: timestamps.map(t => {
              const sample = processData.find(d => d.t === t && d.name === proc);
              return sample ? sample.mem : null;
            }),
            borderColor: colors[i % colors.length],
            tension: 0.1
          }))
        },
        options: { ...chartDefaults, plugins: { ...chartDefaults.plugins, title: { display: true, text: 'Process Memory MB', color: '#eee' } } }
      });
    }

    // .NET Heap Chart
    if (dotnetData.length > 0 && document.getElementById('dotnetHeapChart')) {
      const apps = [...new Set(dotnetData.map(d => d.app))];
      const colors = ['#e94560', '#4ade80', '#60a5fa'];

      new Chart(document.getElementById('dotnetHeapChart'), {
        type: 'line',
        data: {
          labels: dotnetData.filter(d => d.app === apps[0]).map(d => new Date(d.t).toLocaleTimeString()),
          datasets: apps.map((app, i) => ({
            label: app + ' Heap MB',
            data: dotnetData.filter(d => d.app === app).map(d => d.heap),
            borderColor: colors[i % colors.length],
            tension: 0.1
          }))
        },
        options: chartDefaults
      });
    }

    // .NET GC Chart
    if (dotnetData.length > 0 && document.getElementById('dotnetGcChart')) {
      new Chart(document.getElementById('dotnetGcChart'), {
        type: 'line',
        data: {
          labels: dotnetData.map(d => new Date(d.t).toLocaleTimeString()),
          datasets: [
            { label: 'Gen0/s', data: dotnetData.map(d => d.gen0), borderColor: '#4ade80', tension: 0.1 },
            { label: 'Gen1/s', data: dotnetData.map(d => d.gen1), borderColor: '#fbbf24', tension: 0.1 },
            { label: 'Gen2/s', data: dotnetData.map(d => d.gen2), borderColor: '#e94560', tension: 0.1 }
          ]
        },
        options: chartDefaults
      });
    }

    // HTTP Chart
    if (httpData.length > 0 && document.getElementById('httpChart')) {
      new Chart(document.getElementById('httpChart'), {
        type: 'line',
        data: {
          labels: httpData.map(d => new Date(d.t).toLocaleTimeString()),
          datasets: [
            { label: 'Requests', data: httpData.map(d => d.count), borderColor: '#60a5fa', tension: 0.1 },
            { label: 'Latency ms', data: httpData.map(d => d.latency), borderColor: '#e94560', yAxisID: 'y1', tension: 0.1 }
          ]
        },
        options: {
          ...chartDefaults,
          scales: {
            ...chartDefaults.scales,
            y1: { position: 'right', ticks: { color: '#888' }, grid: { drawOnChartArea: false } }
          }
        }
      });
    }

    // SQL Chart
    if (sqlData.length > 0 && document.getElementById('sqlChart')) {
      new Chart(document.getElementById('sqlChart'), {
        type: 'line',
        data: {
          labels: sqlData.map(d => new Date(d.t).toLocaleTimeString()),
          datasets: [
            { label: 'Active Requests', data: sqlData.map(d => d.active), borderColor: '#60a5fa', tension: 0.1 },
            { label: 'Wait Time ms', data: sqlData.map(d => d.wait), borderColor: '#e94560', yAxisID: 'y1', tension: 0.1 },
            { label: 'Blocked', data: sqlData.map(d => d.blocked), borderColor: '#fbbf24', tension: 0.1 }
          ]
        },
        options: {
          ...chartDefaults,
          scales: {
            ...chartDefaults.scales,
            y1: { position: 'right', ticks: { color: '#888' }, grid: { drawOnChartArea: false } }
          }
        }
      });
    }
");
        sb.AppendLine("  </script>");
    }

    private static string HtmlEncode(string? text)
    {
        if (string.IsNullOrEmpty(text)) return "";
        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;")
            .Replace("'", "&#39;");
    }
}
